/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as HistorialCotizacionesRouteImport } from './routes/historial-cotizaciones'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as KaizenRouteImport } from './routes/kaizen'
import { Route as NuevaCotizacionRouteImport } from './routes/nueva-cotizacion'
import { Route as NuevaVentaRouteImport } from './routes/nueva-venta'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SetupClientesRouteImport } from './routes/setup-clientes'
import { Route as SetupProductosRouteImport } from './routes/setup-productos'
import { Route as ApiClientConfigRouteImport } from './routes/api/client-config'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiSetupCustomersRouteImport } from './routes/api/setup-customers'
import { Route as ApiSetupProductsRouteImport } from './routes/api/setup-products'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialCotizacionesRoute = HistorialCotizacionesRouteImport.update({
  id: '/historial-cotizaciones',
  path: '/historial-cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const KaizenRoute = KaizenRouteImport.update({
  id: '/kaizen',
  path: '/kaizen',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaCotizacionRoute = NuevaCotizacionRouteImport.update({
  id: '/nueva-cotizacion',
  path: '/nueva-cotizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaVentaRoute = NuevaVentaRouteImport.update({
  id: '/nueva-venta',
  path: '/nueva-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupClientesRoute = SetupClientesRouteImport.update({
  id: '/setup-clientes',
  path: '/setup-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProductosRoute = SetupProductosRouteImport.update({
  id: '/setup-productos',
  path: '/setup-productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientConfigRoute = ApiClientConfigRouteImport.update({
  id: '/api/client-config',
  path: '/api/client-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupCustomersRoute = ApiSetupCustomersRouteImport.update({
  id: '/api/setup-customers',
  path: '/api/setup-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupProductsRoute = ApiSetupProductsRouteImport.update({
  id: '/api/setup-products',
  path: '/api/setup-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/setup'
    | '/api/setup-customers'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/setup'
    | '/api/setup-customers'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/setup'
    | '/api/setup-customers'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CotizacionesRoute: typeof CotizacionesRoute
  HistorialRoute: typeof HistorialRoute
  HistorialCotizacionesRoute: typeof HistorialCotizacionesRoute
  InventarioRoute: typeof InventarioRoute
  KaizenRoute: typeof KaizenRoute
  NuevaCotizacionRoute: typeof NuevaCotizacionRoute
  NuevaVentaRoute: typeof NuevaVentaRoute
  SetupRoute: typeof SetupRoute
  SetupClientesRoute: typeof SetupClientesRoute
  SetupProductosRoute: typeof SetupProductosRoute
  ApiClientConfigRoute: typeof ApiClientConfigRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiSetupCustomersRoute: typeof ApiSetupCustomersRoute
  ApiSetupProductsRoute: typeof ApiSetupProductsRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial-cotizaciones': {
      id: '/historial-cotizaciones'
      path: '/historial-cotizaciones'
      fullPath: '/historial-cotizaciones'
      preLoaderRoute: typeof HistorialCotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaizen': {
      id: '/kaizen'
      path: '/kaizen'
      fullPath: '/kaizen'
      preLoaderRoute: typeof KaizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-cotizacion': {
      id: '/nueva-cotizacion'
      path: '/nueva-cotizacion'
      fullPath: '/nueva-cotizacion'
      preLoaderRoute: typeof NuevaCotizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-venta': {
      id: '/nueva-venta'
      path: '/nueva-venta'
      fullPath: '/nueva-venta'
      preLoaderRoute: typeof NuevaVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-clientes': {
      id: '/setup-clientes'
      path: '/setup-clientes'
      fullPath: '/setup-clientes'
      preLoaderRoute: typeof SetupClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-productos': {
      id: '/setup-productos'
      path: '/setup-productos'
      fullPath: '/setup-productos'
      preLoaderRoute: typeof SetupProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-config': {
      id: '/api/client-config'
      path: '/api/client-config'
      fullPath: '/api/client-config'
      preLoaderRoute: typeof ApiClientConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-customers': {
      id: '/api/setup-customers'
      path: '/api/setup-customers'
      fullPath: '/api/setup-customers'
      preLoaderRoute: typeof ApiSetupCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-products': {
      id: '/api/setup-products'
      path: '/api/setup-products'
      fullPath: '/api/setup-products'
      preLoaderRoute: typeof ApiSetupProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CotizacionesRoute: CotizacionesRoute,
  HistorialRoute: HistorialRoute,
  HistorialCotizacionesRoute: HistorialCotizacionesRoute,
  InventarioRoute: InventarioRoute,
  KaizenRoute: KaizenRoute,
  NuevaCotizacionRoute: NuevaCotizacionRoute,
  NuevaVentaRoute: NuevaVentaRoute,
  SetupRoute: SetupRoute,
  SetupClientesRoute: SetupClientesRoute,
  SetupProductosRoute: SetupProductosRoute,
  ApiClientConfigRoute: ApiClientConfigRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiSetupCustomersRoute: ApiSetupCustomersRoute,
  ApiSetupProductsRoute: ApiSetupProductsRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
