/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as HistorialCotizacionesRouteImport } from './routes/historial-cotizaciones'
import { Route as InstaladorRouteImport } from './routes/instalador'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as KaizenRouteImport } from './routes/kaizen'
import { Route as NuevaCotizacionRouteImport } from './routes/nueva-cotizacion'
import { Route as NuevaVentaRouteImport } from './routes/nueva-venta'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SetupClientesRouteImport } from './routes/setup-clientes'
import { Route as SetupConexionRouteImport } from './routes/setup-conexion'
import { Route as SetupProductosRouteImport } from './routes/setup-productos'
import { Route as ApiClientConfigRouteImport } from './routes/api/client-config'
import { Route as ApiInstallerStatusRouteImport } from './routes/api/installer-status'
import { Route as ApiMigrateOperationalConnectionRouteImport } from './routes/api/migrate-operational-connection'
import { Route as ApiRuntimeBootstrapRouteImport } from './routes/api/runtime-bootstrap'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiSetupClientContextRouteImport } from './routes/api/setup-client-context'
import { Route as ApiSetupConnectionRouteImport } from './routes/api/setup-connection'
import { Route as ApiSetupCustomersRouteImport } from './routes/api/setup-customers'
import { Route as ApiSetupOperationalConnectionRouteImport } from './routes/api/setup-operational-connection'
import { Route as ApiSetupProductsRouteImport } from './routes/api/setup-products'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialCotizacionesRoute = HistorialCotizacionesRouteImport.update({
  id: '/historial-cotizaciones',
  path: '/historial-cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InstaladorRoute = InstaladorRouteImport.update({
  id: '/instalador',
  path: '/instalador',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const KaizenRoute = KaizenRouteImport.update({
  id: '/kaizen',
  path: '/kaizen',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaCotizacionRoute = NuevaCotizacionRouteImport.update({
  id: '/nueva-cotizacion',
  path: '/nueva-cotizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaVentaRoute = NuevaVentaRouteImport.update({
  id: '/nueva-venta',
  path: '/nueva-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupClientesRoute = SetupClientesRouteImport.update({
  id: '/setup-clientes',
  path: '/setup-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupConexionRoute = SetupConexionRouteImport.update({
  id: '/setup-conexion',
  path: '/setup-conexion',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProductosRoute = SetupProductosRouteImport.update({
  id: '/setup-productos',
  path: '/setup-productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientConfigRoute = ApiClientConfigRouteImport.update({
  id: '/api/client-config',
  path: '/api/client-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstallerStatusRoute = ApiInstallerStatusRouteImport.update({
  id: '/api/installer-status',
  path: '/api/installer-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMigrateOperationalConnectionRoute =
  ApiMigrateOperationalConnectionRouteImport.update({
    id: '/api/migrate-operational-connection',
    path: '/api/migrate-operational-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRuntimeBootstrapRoute = ApiRuntimeBootstrapRouteImport.update({
  id: '/api/runtime-bootstrap',
  path: '/api/runtime-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupClientContextRoute = ApiSetupClientContextRouteImport.update({
  id: '/api/setup-client-context',
  path: '/api/setup-client-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupConnectionRoute = ApiSetupConnectionRouteImport.update({
  id: '/api/setup-connection',
  path: '/api/setup-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupCustomersRoute = ApiSetupCustomersRouteImport.update({
  id: '/api/setup-customers',
  path: '/api/setup-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupOperationalConnectionRoute =
  ApiSetupOperationalConnectionRouteImport.update({
    id: '/api/setup-operational-connection',
    path: '/api/setup-operational-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSetupProductsRoute = ApiSetupProductsRouteImport.update({
  id: '/api/setup-products',
  path: '/api/setup-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/instalador': typeof InstaladorRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-conexion': typeof SetupConexionRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/installer-status': typeof ApiInstallerStatusRoute
  '/api/migrate-operational-connection': typeof ApiMigrateOperationalConnectionRoute
  '/api/runtime-bootstrap': typeof ApiRuntimeBootstrapRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-client-context': typeof ApiSetupClientContextRoute
  '/api/setup-connection': typeof ApiSetupConnectionRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-operational-connection': typeof ApiSetupOperationalConnectionRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/instalador': typeof InstaladorRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-conexion': typeof SetupConexionRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/installer-status': typeof ApiInstallerStatusRoute
  '/api/migrate-operational-connection': typeof ApiMigrateOperationalConnectionRoute
  '/api/runtime-bootstrap': typeof ApiRuntimeBootstrapRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-client-context': typeof ApiSetupClientContextRoute
  '/api/setup-connection': typeof ApiSetupConnectionRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-operational-connection': typeof ApiSetupOperationalConnectionRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/historial': typeof HistorialRoute
  '/historial-cotizaciones': typeof HistorialCotizacionesRoute
  '/instalador': typeof InstaladorRoute
  '/inventario': typeof InventarioRoute
  '/kaizen': typeof KaizenRoute
  '/nueva-cotizacion': typeof NuevaCotizacionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/setup': typeof SetupRoute
  '/setup-clientes': typeof SetupClientesRoute
  '/setup-conexion': typeof SetupConexionRoute
  '/setup-productos': typeof SetupProductosRoute
  '/api/client-config': typeof ApiClientConfigRoute
  '/api/installer-status': typeof ApiInstallerStatusRoute
  '/api/migrate-operational-connection': typeof ApiMigrateOperationalConnectionRoute
  '/api/runtime-bootstrap': typeof ApiRuntimeBootstrapRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/setup-client-context': typeof ApiSetupClientContextRoute
  '/api/setup-connection': typeof ApiSetupConnectionRoute
  '/api/setup-customers': typeof ApiSetupCustomersRoute
  '/api/setup-operational-connection': typeof ApiSetupOperationalConnectionRoute
  '/api/setup-products': typeof ApiSetupProductsRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/instalador'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-conexion'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/installer-status'
    | '/api/migrate-operational-connection'
    | '/api/runtime-bootstrap'
    | '/api/setup'
    | '/api/setup-client-context'
    | '/api/setup-connection'
    | '/api/setup-customers'
    | '/api/setup-operational-connection'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/instalador'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-conexion'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/installer-status'
    | '/api/migrate-operational-connection'
    | '/api/runtime-bootstrap'
    | '/api/setup'
    | '/api/setup-client-context'
    | '/api/setup-connection'
    | '/api/setup-customers'
    | '/api/setup-operational-connection'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cotizaciones'
    | '/historial'
    | '/historial-cotizaciones'
    | '/instalador'
    | '/inventario'
    | '/kaizen'
    | '/nueva-cotizacion'
    | '/nueva-venta'
    | '/setup'
    | '/setup-clientes'
    | '/setup-conexion'
    | '/setup-productos'
    | '/api/client-config'
    | '/api/installer-status'
    | '/api/migrate-operational-connection'
    | '/api/runtime-bootstrap'
    | '/api/setup'
    | '/api/setup-client-context'
    | '/api/setup-connection'
    | '/api/setup-customers'
    | '/api/setup-operational-connection'
    | '/api/setup-products'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CotizacionesRoute: typeof CotizacionesRoute
  HistorialRoute: typeof HistorialRoute
  HistorialCotizacionesRoute: typeof HistorialCotizacionesRoute
  InstaladorRoute: typeof InstaladorRoute
  InventarioRoute: typeof InventarioRoute
  KaizenRoute: typeof KaizenRoute
  NuevaCotizacionRoute: typeof NuevaCotizacionRoute
  NuevaVentaRoute: typeof NuevaVentaRoute
  SetupRoute: typeof SetupRoute
  SetupClientesRoute: typeof SetupClientesRoute
  SetupConexionRoute: typeof SetupConexionRoute
  SetupProductosRoute: typeof SetupProductosRoute
  ApiClientConfigRoute: typeof ApiClientConfigRoute
  ApiInstallerStatusRoute: typeof ApiInstallerStatusRoute
  ApiMigrateOperationalConnectionRoute: typeof ApiMigrateOperationalConnectionRoute
  ApiRuntimeBootstrapRoute: typeof ApiRuntimeBootstrapRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiSetupClientContextRoute: typeof ApiSetupClientContextRoute
  ApiSetupConnectionRoute: typeof ApiSetupConnectionRoute
  ApiSetupCustomersRoute: typeof ApiSetupCustomersRoute
  ApiSetupOperationalConnectionRoute: typeof ApiSetupOperationalConnectionRoute
  ApiSetupProductsRoute: typeof ApiSetupProductsRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial-cotizaciones': {
      id: '/historial-cotizaciones'
      path: '/historial-cotizaciones'
      fullPath: '/historial-cotizaciones'
      preLoaderRoute: typeof HistorialCotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalador': {
      id: '/instalador'
      path: '/instalador'
      fullPath: '/instalador'
      preLoaderRoute: typeof InstaladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaizen': {
      id: '/kaizen'
      path: '/kaizen'
      fullPath: '/kaizen'
      preLoaderRoute: typeof KaizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-cotizacion': {
      id: '/nueva-cotizacion'
      path: '/nueva-cotizacion'
      fullPath: '/nueva-cotizacion'
      preLoaderRoute: typeof NuevaCotizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-venta': {
      id: '/nueva-venta'
      path: '/nueva-venta'
      fullPath: '/nueva-venta'
      preLoaderRoute: typeof NuevaVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-clientes': {
      id: '/setup-clientes'
      path: '/setup-clientes'
      fullPath: '/setup-clientes'
      preLoaderRoute: typeof SetupClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-conexion': {
      id: '/setup-conexion'
      path: '/setup-conexion'
      fullPath: '/setup-conexion'
      preLoaderRoute: typeof SetupConexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-productos': {
      id: '/setup-productos'
      path: '/setup-productos'
      fullPath: '/setup-productos'
      preLoaderRoute: typeof SetupProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-config': {
      id: '/api/client-config'
      path: '/api/client-config'
      fullPath: '/api/client-config'
      preLoaderRoute: typeof ApiClientConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/installer-status': {
      id: '/api/installer-status'
      path: '/api/installer-status'
      fullPath: '/api/installer-status'
      preLoaderRoute: typeof ApiInstallerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/migrate-operational-connection': {
      id: '/api/migrate-operational-connection'
      path: '/api/migrate-operational-connection'
      fullPath: '/api/migrate-operational-connection'
      preLoaderRoute: typeof ApiMigrateOperationalConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime-bootstrap': {
      id: '/api/runtime-bootstrap'
      path: '/api/runtime-bootstrap'
      fullPath: '/api/runtime-bootstrap'
      preLoaderRoute: typeof ApiRuntimeBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-client-context': {
      id: '/api/setup-client-context'
      path: '/api/setup-client-context'
      fullPath: '/api/setup-client-context'
      preLoaderRoute: typeof ApiSetupClientContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-connection': {
      id: '/api/setup-connection'
      path: '/api/setup-connection'
      fullPath: '/api/setup-connection'
      preLoaderRoute: typeof ApiSetupConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-customers': {
      id: '/api/setup-customers'
      path: '/api/setup-customers'
      fullPath: '/api/setup-customers'
      preLoaderRoute: typeof ApiSetupCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-operational-connection': {
      id: '/api/setup-operational-connection'
      path: '/api/setup-operational-connection'
      fullPath: '/api/setup-operational-connection'
      preLoaderRoute: typeof ApiSetupOperationalConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-products': {
      id: '/api/setup-products'
      path: '/api/setup-products'
      fullPath: '/api/setup-products'
      preLoaderRoute: typeof ApiSetupProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CotizacionesRoute: CotizacionesRoute,
  HistorialRoute: HistorialRoute,
  HistorialCotizacionesRoute: HistorialCotizacionesRoute,
  InstaladorRoute: InstaladorRoute,
  InventarioRoute: InventarioRoute,
  KaizenRoute: KaizenRoute,
  NuevaCotizacionRoute: NuevaCotizacionRoute,
  NuevaVentaRoute: NuevaVentaRoute,
  SetupRoute: SetupRoute,
  SetupClientesRoute: SetupClientesRoute,
  SetupConexionRoute: SetupConexionRoute,
  SetupProductosRoute: SetupProductosRoute,
  ApiClientConfigRoute: ApiClientConfigRoute,
  ApiInstallerStatusRoute: ApiInstallerStatusRoute,
  ApiMigrateOperationalConnectionRoute: ApiMigrateOperationalConnectionRoute,
  ApiRuntimeBootstrapRoute: ApiRuntimeBootstrapRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiSetupClientContextRoute: ApiSetupClientContextRoute,
  ApiSetupConnectionRoute: ApiSetupConnectionRoute,
  ApiSetupCustomersRoute: ApiSetupCustomersRoute,
  ApiSetupOperationalConnectionRoute: ApiSetupOperationalConnectionRoute,
  ApiSetupProductsRoute: ApiSetupProductsRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
